[package]
name = "dwarfer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dwarfer"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
axum = { version = "0.6.0", optional = true }
clap = { version = "4.6.1", features = ["derive"], optional = true }
config = { version = "0.15.23" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
toml = "0.9.8"
async-trait = { version = "0.1" }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls"], optional = true }
redis = { version = "0.23", optional = true }
validator = { version = "0.20.0" }
nanoid = { version = "0.5" }
chrono = { version = "0.4.45", features = ["serde"] }
anyhow = "1.0"
regex = "1.10"
thiserror = "2.0.18"

[features]
default = ["cli", "repo-sqlite", "auth-api-key", "api-full"]
api-redirect = ["axum"]
api-full = ["axum"]
cli = ["clap"]
repo-file = []
repo-sqlite = ["sqlx", "_db"]
repo-redis = ["redis", "_db"]
repo-postgres = ["sqlx", "_db"]
repo-mongo = ["_db"]
auth-api-key = []
repo-http-remote = []
_db = []
